repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.11
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
-   repo: https://github.com/psf/black
    rev: '23.12.1'
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.5.0'
    hooks:
    -   id: check-ast
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-toml
