# @package _global_

model_name: "mVAE"

model:
  z_dim: 10
  beta: 1
  join_type: "PoE"
  sparse: True
  threshold: 0.2
  warmup: 10
  learning_rate: 0.001
  use_prior: True
  weight_ll: False

datamodule:
  _target_: multiviewae.base.dataloaders.MultiviewDataModule
  is_validate: False

encoder:
  default:
    _target_: multiviewae.architectures.mlp.VariationalEncoder
    bias: True
    non_linear: True
    hidden_layer_dim: [40, 20]
    enc_dist:
      _target_: multiviewae.base.distributions.Normal
decoder:
  default:
    _target_: multiviewae.architectures.mlp.VariationalDecoder
    bias: True
    non_linear: True
    hidden_layer_dim: [20, 40]
    init_logvar: -3
    dec_dist:
      _target_: multiviewae.base.distributions.Normal
prior:
  _target_: multiviewae.base.distributions.Normal
  loc: 0.0
  scale: 1.0
trainer:
  _target_: pytorch_lightning.Trainer
  gpus: 0
  max_epochs: 10
  deterministic: False
  log_every_n_steps: 2
  resume_from_checkpoint: null #${out_dir}/last.ckpt
callbacks:
  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: "val_loss"
    mode: "min"
    save_last: True
  early_stopping:
    _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: "val_loss"
    mode: "min"
    patience: 50
    min_delta: 0.001
    verbose: True
